version: '3'

includes:
  fish: ./fish.d/Taskfile_{{OS}}.yml
  git: ./git.d
  karabiner: ./karabiner.d/Taskfile_{{OS}}.yml
  skhd: ./skhd.d/Taskfile_{{OS}}.yml
  starship: ./starship.d
  yabai: ./yabai.d/Taskfile_{{OS}}.yml

tasks:
  clean:
    deps:
      - fish:clean
      - git:clean
      - karabiner:clean
      - skhd:clean
      - starship:clean
      - yabai:clean

  install:
    deps:
      - fish:install
      - git:install
      - karabiner:install
      - skhd:install
      - starship:install
      - yabai:install
