version: '3'

includes:
  fish:
    dir: ./fish.d
    taskfile: ./fish.d/Taskfile_{{OS}}.yml
  git:
    dir: ./git.d
    taskfile: ./git.d
  karabiner:
    dir: ./karabiner.d
    taskfile: ./karabiner.d/Taskfile_{{OS}}.yml
  skhd:
    dir: ./skhd.d
    taskfile: ./skhd.d/Taskfile_{{OS}}.yml
  starship:
    dir: ./starship.d
    taskfile: ./starship.d
  yabai:
    dir: ./yabai.d
    taskfile: ./yabai.d/Taskfile_{{OS}}.yml

tasks:
  clean:
    deps:
      - fish:clean
      - git:clean
      - karabiner:clean
      - skhd:clean
      - starship:clean
      - yabai:clean

  install:
    deps:
      - fish:install
      - git:install
      - karabiner:install
      - skhd:install
      - starship:install
      - yabai:install
