source ~/.files/zsh.d/packages
source ~/.files/zsh.d/prompt

# Lines configured by zsh-newuser-install
bindkey -v
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle ':compinstall' filename '~/.zshrc'
zstyle ':completion:*' completer _oldlist _complete
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd ..
zstyle ':completion:*:descriptions' format 'completing %B%d%b'
zstyle ':completion:*:options' description 'yes'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt auto_cd
setopt auto_pushd
setopt correct
setopt extended_glob
setopt extended_history
setopt hist_expand
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt inc_append_history
setopt long_list_jobs
setopt magic_equal_subst
setopt no_beep
setopt noflowcontrol
setopt noignoreeof
setopt share_history
setopt transient_rprompt

alias tmux="tmux -2"

case $OSTYPE in
  linux*)
    alias la="ls -lhAF --color=auto"
  ;;
  freebsd*|darwin*)
    alias la="ls -lhAFG"
  ;;
esac

if [ -x $(which vim) ]; then
  alias vi="vim"
fi

bindkey '^Q' push-line-or-edit
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^S' history-incremental-pattern-search-forward

bindkey -M afu '^H' backward-word
bindkey -M afu '^L' forward-word
bindkey -M afu '^R' zaw-history
bindkey -M afu '^Z' zaw
bindkey -M afu '^[^[' afu+vi-cmd-mode
bindkey -M afu '^[^L' clear-screen

bindkey -M afu-vicmd 'k' history-substring-search-up
bindkey -M afu-vicmd 'j' history-substring-search-down

HISTFILE=~/.histfile
HISTSIZE=100
REPORT_TIME=3
SAVEHIST=100000

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
who
