version: '3'

vars:
  TARGET: "{{.XDG_CONFIG_HOME}}/alacritty/alacritty.yml"

tasks:
  clean:
    cmds:
      - unlink "{{.TARGET}}"
    status:
      - test -h "{{.TARGET}}"

  install:
    cmds:
      - ln -s "{{.CWD}}/alacritty.yml" "{{.TARGET}}"
    status:
      - test -e "{{.TARGET}}"
    vars:
      CWD:
        sh: pwd
