version: '3'

vars:
  TARGET: "~/.gitconfig"

tasks:
  clean:
    cmds:
      - unlink "{{.TARGET}}"
    status:
      - test -h "{{.TARGET}}"

  install:
    cmds:
      - ln -s "{{.CWD}}/gitconfig" "{{.TARGET}}"
    status:
      - test -h "{{.TARGET}}"
    vars:
      CWD:
        sh: pwd
