version: '3'

tasks:
  clean:
    vars:
      TARGET: "{{.HOME}}/.gitconfig"
    cmds:
      - unlink "{{.TARGET}}"
    status:
      - test -h "{{.TARGET}}"

  install:
    cmds:
      - ln -s "{{.CWD}}/gitconfig" "{{.TARGET}}"
    status:
      - test -h "{{.TARGET}}"
    vars:
      CWD:
        sh: pwd
      TARGET: "{{.HOME}}/.gitconfig"
