version: '3'

tasks:
  clean:
    cmds:
      - unlink "{{.TARGET}}"
    status:
      - test ! -L "{{.TARGET}}"
    vars:
      TARGET: "{{.XDG_CONFIG_HOME}}/starship.toml"

  install:
    cmds:
      - ln -s "{{.CWD}}/starship.toml" "{{.TARGET}}"
    status:
      - test -L "{{.TARGET}}"
    vars:
      CWD:
        sh: pwd
      TARGET: "{{.XDG_CONFIG_HOME}}/starship.toml"
